spring: 
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: usu1
        password: usu1
        driver-class-name: oracle.jdbc.driver.OracleDriver
        driver:
            class: oracle.jdbc.driver.OracleDriver

#spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
    jpa:
        hibernate: 
            ddl-auto: none
server:
  port: 8975
